package org.personal.concurrency.model;

import jakarta.persistence.EntityManager;
import jakarta.transaction.Transactional;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.personal.concurrency.config.TestConfig;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(SpringExtension.class)
@SpringBootTest(classes = TestConfig.class)
@ActiveProfiles("test")
class CustomersEntityTest {

    @Autowired
    private EntityManager entityManager;

    @Test
    @Transactional
    void verifyCustomerIdAutoGenerated() {
        CustomersEntity customerEntity = new CustomersEntity("John", "Doe", "john.doe@example.com");
        entityManager.persist(customerEntity);
        entityManager.flush();

        assertNotNull(customerEntity.getCustomerId());
        System.out.println(customerEntity.getCustomerId());
    }
}